version: "3.1"
services:
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: localdb
    cap_add:
      - SYS_NICE
    ports:
      - 3306:3306
    volumes:
      - database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  database:
